// E09-S03-T06 — `fetch-artifacts.sh`, the generated project's artifact refresh.
//
// docs/04 §7 specifies the shape in one sentence: the script "uses `azdo-emu` if installed, else
// documented `curl` + `SYSTEM_ACCESSTOKEN` fallback". Both halves are deliberate.
//
// **Why the fallback is documentation rather than an implementation.** Downloading an artifact is
// two requests: metadata with `$expand=signedContent`, then the signed URL itself. Extracting
// `signedContent.url` from the first response means parsing JSON, and the generated project is
// dependency-free bash (PLAN D2) — `jq` is not guaranteed. A hand-rolled `grep`/`sed` extractor
// would be one bad match away from printing a **bearer credential** into a terminal, which is
// precisely what C-E09-094 is about. So the fallback prints the two commands and lets the operator
// run them; the Do field and docs/04 both say *documented*, and this is why.
const FETCH_ARTIFACTS_SH = `#!/usr/bin/env bash
# fetch-artifacts.sh — re-download the pipeline artifacts this project pins.
#
# Generated by azdo-emu. The pins live in \`azdo-emu.lock.json\` as
# \`pipelines.<alias>.{pipelineId, runId, artifacts}\`; downloads land in
# \`.cache/artifacts/<alias>/<runId>/<artifactName>/\`, which is where the runtime reads them.
#
# Usage: bash fetch-artifacts.sh [--refresh] [--latest]
#   --refresh   re-download even when the cache is already warm
#   --latest    resolve each pin to its pipeline's newest completed run instead of the pinned
#               \`runId\`. The download lands under that run's own cache directory, so it never
#               overwrites the pinned one — and a \`--frozen\` convert still uses the pin. Use
#               \`azdo-emu convert --update\` to move a pin.
set -euo pipefail

here="$(cd -- "$(dirname -- "\${BASH_SOURCE[0]}")" && pwd)"

# The converter owns the auth chain (interactive / az / PAT, docs/05 §1), the lockfile reader and
# the cache layout. When it is on PATH there is nothing for this script to reimplement.
if command -v azdo-emu >/dev/null 2>&1; then
  exec azdo-emu fetch-artifacts "$here" "$@"
fi

# Quoted heredoc: every \`$\` below must reach the reader literally. An unquoted one would expand
# $SYSTEM_ACCESSTOKEN and print the operator's own token into their terminal.
cat <<'FALLBACK' >&2
azdo-emu is not on PATH, so this script cannot fetch anything itself.

Install it (\`npm i -g azdo-emu\`) and re-run, or fetch by hand with curl. For each artifact in
azdo-emu.lock.json — pipelines.<alias>.{pipelineId, runId, artifacts} — two requests:

  # 1. metadata. A PAT is HTTP Basic with an EMPTY username (curl -u :TOKEN).
  curl -sS -u ":$SYSTEM_ACCESSTOKEN" \\
    "$AZDO_ORG_URL/$AZDO_PROJECT/_apis/pipelines/<pipelineId>/runs/<runId>/artifacts?artifactName=<artifactName>&\\$expand=signedContent&api-version=7.1"

  # 2. download. NO Authorization header: the signature in the URL is the grant, and adding
  #    credentials to a pre-signed URL is how some services reject it outright.
  curl -sS -o artifact.zip "<signedContent.url from step 1>"

  # 3. unpack into the layout the runtime expects.
  mkdir -p .cache/artifacts/<alias>/<runId>/<artifactName>
  unzip -q artifact.zip -d .cache/artifacts/<alias>/<runId>/<artifactName>

Treat the step-1 response as a secret. signedContent.url is a time-limited bearer credential, and
its *path* carries a base64 segment that decodes to your organization name — so it survives a
search-and-replace for that name. Do not paste it into a log, an issue or a chat.
FALLBACK
exit 1
`;

/**
 * The project-level artifact refresh script.
 *
 * Constant rather than pipeline-derived: it reads `azdo-emu.lock.json` at *run* time, so baking
 * today's pins into it would go stale the moment a pin moved, and every generated project would
 * differ in a file whose content is the same procedure.
 */
export function emitFetchArtifactsScript(): string {
  return FETCH_ARTIFACTS_SH;
}
