// E04-S02-T03 — the predefined-variable table, as vendored data.
//
// The table is generated by `pnpm predefined-vars` from the docs repository at a pinned commit, not
// scraped from the rendered page: `learn.microsoft.com` builds the table through an `[!INCLUDE]`,
// so the rendered HTML has no version to pin, while `MicrosoftDocs/azure-devops-docs` does. That is
// what makes "a re-run produces stable output" a property rather than a hope (C-E04-093).
//
// This module is only the reader. It exists so the set that E04-S02-T02's classifier takes as an
// injected port has one obvious source, rather than each consumer parsing the JSON itself.
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

export interface PredefinedVariable {
  readonly name: string;
  /** Doc section the row came from, e.g. `Agent variables`. */
  readonly section: string;
  /** Deep link to that section on the rendered page. */
  readonly anchor: string;
  readonly description: string;
  /**
   * `Build.Clean` and `System.Debug` only — the page's own stated exceptions to "automatically set
   * by the system and read-only" (C-E04-095). Every other predefined name is read-only.
   */
  readonly writable?: true;
}

export interface PredefinedTable {
  readonly source: {
    readonly repo: string;
    readonly path: string;
    readonly commit: string;
    readonly pagePath: string;
    readonly pageCommit: string;
    readonly page: string;
    readonly generatedBy: string;
  };
  readonly variables: readonly PredefinedVariable[];
}

/**
 * Absolute path of the generated table, walking up from this module to the package root.
 *
 * The same shape as `vendoredSchemaPath()` and for the same reason: a fixed `../../` is correct
 * from `src/model/` and wrong from the bundled `dist/index.js`, which sits one level deep. Walking
 * up finds it from either.
 */
export function predefinedTablePath(): string {
  let dir = import.meta.dirname;
  for (let i = 0; i < 6; i++) {
    const candidate = path.join(dir, 'data', 'predefined-vars.json');
    if (existsSync(candidate)) return candidate;
    dir = path.dirname(dir);
  }
  throw new Error(
    'predefined-vars.json not found (expected under packages/engine/data; run `pnpm predefined-vars`)',
  );
}

let cached: PredefinedTable | undefined;

/** The generated table. Read once and memoised — it is a build artifact, not live state. */
export function predefinedTable(): PredefinedTable {
  cached ??= JSON.parse(readFileSync(predefinedTablePath(), 'utf8')) as PredefinedTable;
  return cached;
}

/**
 * Folded names, for `classifyVariables({ predefined })`.
 *
 * Folded because variable names are case-insensitive to match the agent's dictionary (C-E06-003) —
 * the classifier folds too, so handing it raw names would work by luck rather than by contract.
 */
export function predefinedNames(): ReadonlySet<string> {
  return new Set(predefinedTable().variables.map((entry) => entry.name.toLowerCase()));
}

/** One row by name, case-insensitively. */
export function predefinedVariable(name: string): PredefinedVariable | undefined {
  const folded = name.toLowerCase();
  return predefinedTable().variables.find((entry) => entry.name.toLowerCase() === folded);
}

/**
 * Is this a predefined name a pipeline may legitimately assign to?
 *
 * Only the two the page names (C-E04-095). Anything else being written is a pipeline bug the
 * converter can point at rather than silently reproduce.
 */
export function isWritablePredefined(name: string): boolean {
  return predefinedVariable(name)?.writable === true;
}
