/**
 * E10-S02-T01 — `convert`: the wiring that turns every other epic into a generated project.
 *
 * Nothing here is new behaviour. Every step below is a module that already exists and was already
 * tested against the service; what was missing was the thing that calls them in order, which is why
 * `convert`'s body threw `NotImplementedError` while seven epics' worth of machinery sat behind it.
 *
 * The order is forced by what each step needs:
 *
 *   config → bundle → expand → validate → model → emit → write
 *
 *  - **bundle before expand** (E03-S06): the service reads *committed* bytes, so local template
 *    edits only reach it by being spliced into the override first. A reference the bundler refuses
 *    is a warning that rides all the way into the generated README (C-E03-411/412).
 *  - **expand, not evaluate** (PLAN D3): the service is the authority. `--offline-expand` is the
 *    only way to the retained local engine, and it is labelled degraded everywhere it appears.
 *  - **validate the expansion, not the source** (E03-S04-T03): the expanded document is a different
 *    dialect and has its own validator.
 *
 * Four things this task inherited from earlier decision entries, each deferred *to here* by name and
 * none of them optional if the generated project is to run at all:
 *
 *  - `lib/runtime.sh` + `lib/expr.sh`, the runtime copied into the project (decision 62).
 *  - `.shellcheckrc`, carrying the four codes decisions 61 and 62(d) established (C-E06-018/024).
 *  - the manifest's per-step `file` and per-job `targetOs` fills (decision 64).
 *  - binding the engine's `expandDocument` as the `OfflineExpander` port (E03-S04-T02/T03).
 */
import { cpSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

import {
  buildPipeline,
  expandDocument,
  inlineTemplates,
  parsePipelineYaml,
  serializeManifest,
  validateExpandedPipeline,
  type Diagnostic,
  type ExpandedDiagnostic,
  type ManifestEnvEntry,
  type ManifestWarning,
  type Pipeline,
  type SerializedManifest,
} from '@azdo-emu/engine';
import {
  collectConnections,
  emitEntrypoints,
  emitStepScript,
  generateReadme,
  loadVendoredTaskDefinitions,
  scaffold,
  synthesizeEnvExample,
  GITIGNORE,
  type Scaffold,
  type StepSite,
} from '@azdo-emu/emit';
import { aggregateTools, type StepToolContext } from '../doctor/requirements.js';
import {
  resolveExpansion,
  type ExpansionManifestEntry,
  type FetchLike,
  type OracleConfig,
} from '@azdo-emu/fetch';

import { CliError, EXIT } from '../exit.js';
import {
  loadConfigFor,
  resolveSettings,
  type CliSettings,
  type ResolvedSettings,
} from '../config/index.js';

/** Bumped when a `--json` consumer would misread an older document. */
export const CONVERT_JSON_VERSION = 1;

/**
 * The generated project's `.shellcheckrc`.
 *
 * Four codes, two decisions, and every one of them is a false positive *by construction* rather
 * than a style choice: `SC2005`/`SC2046` because an ADO `$( )` macro is not a command substitution
 * and the emitter must leave it intact (decision 61, C-E06-018/024), `SC2016`/`SC2071` because
 * `run-job.sh` passes a macro through single-quoted and compares zero-padded step numbers as
 * strings (decision 62(d)). Shipping the file means a user's editor and CI agree with our own gate.
 */
export const SHELLCHECKRC =
  '# Generated by azdo-emu. Every disable here is a false positive by construction:\n' +
  '#   SC2005/SC2046 — `$(name)` is an Azure Pipelines macro the runtime expands, not a command\n' +
  '#     substitution; the emitter must leave it verbatim (docs/06 §5 decision 61).\n' +
  "#   SC2016 — `--wd '$(System.DefaultWorkingDirectory)'` is a macro passthrough `run_step`\n" +
  '#     expands, not bash (decision 62(d)).\n' +
  '#   SC2071 — step numbers are zero-padded `NNN` compared as strings; `-gt` would read `080`\n' +
  '#     as octal (decision 62(d)).\n' +
  'disable=SC2005,SC2046,SC2016,SC2071\n';

export interface ConvertFlags {
  /** `--out`. */
  readonly out: string;
  readonly parameter?: Readonly<Record<string, unknown>> | undefined;
  readonly org?: string | undefined;
  readonly project?: string | undefined;
  readonly targetOs?: CliSettings['targetOs'];
  readonly checkoutMode?: CliSettings['checkoutMode'];
  readonly execEnv?: CliSettings['execEnv'];
  readonly sandboxImage?: string | undefined;
  readonly groupNames?: boolean | undefined;
  readonly onlyStage?: readonly string[] | undefined;
  readonly frozen?: boolean | undefined;
  readonly update?: boolean | undefined;
  readonly offline?: boolean | undefined;
  readonly offlineExpand?: boolean | undefined;
  readonly strict?: boolean | undefined;
  /** `--no-bundle`: commander gives `bundle: false`. */
  readonly bundle?: boolean | undefined;
}

export interface ConvertDeps {
  /** Injected so the service arm is testable without network (`ExpandCachedOptions.fetchImpl`). */
  readonly fetchImpl?: FetchLike | undefined;
  /** Organization/pipeline context for the service arm. Absent = the arm cannot run. */
  readonly oracle?: OracleConfig | undefined;
  /** Where the expansion cache lives; defaults beside the output directory. */
  readonly cacheDir?: string | undefined;
}

export interface ConvertSummary {
  readonly version: number;
  readonly out: string;
  readonly expansion: { readonly mode: string; readonly degraded: boolean };
  readonly stages: number;
  readonly jobs: number;
  readonly steps: number;
  readonly warnings: number;
  readonly errors: number;
  readonly files: number;
}

export interface ConvertResult {
  readonly summary: ConvertSummary;
  readonly warnings: readonly ManifestWarning[];
  readonly diagnostics: readonly ExpandedDiagnostic[];
}

/** `--exec-env sandbox` / `--sandbox-image` name a deferred feature (docs/06 §1, E12-S02-T02). */
function refuseDeferredSandbox(flags: ConvertFlags): void {
  if (flags.execEnv === 'sandbox')
    throw new CliError('sandbox execution is not implemented', {
      hint: 'PLAN D9 was revised: `host` is the only execution environment. Drop `--exec-env sandbox`.',
    });
  if (flags.sandboxImage !== undefined)
    throw new CliError('`--sandbox-image` has no effect: the container sandbox is deferred', {
      hint: 'Drop the flag; the generated project runs on the host (docs/04 §9).',
    });
}

/**
 * `--offline` is a *promise*, not a synonym for `--offline-expand`.
 *
 * docs/06 §1: it is "satisfiable only via `--frozen` over a warm expansion cache or
 * `--offline-expand`". Accepting it on its own would make the CLI reach for the network anyway and
 * fail with a connection error instead of a usage one.
 */
function checkOffline(flags: ConvertFlags): void {
  if (flags.offline !== true) return;
  if (flags.frozen === true || flags.offlineExpand === true) return;
  throw new CliError('`--offline` needs a source that makes no network call', {
    hint: 'Add `--frozen` (resolve the expansion from a warm cache) or `--offline-expand` (degraded local engine).',
  });
}

/** Read the pipeline, or say which file was missing rather than leaking an ENOENT stack. */
function readPipeline(file: string): string {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    throw new CliError(`cannot read pipeline file: ${file}`);
  }
}

/** The bundler's view of the working tree: repository-absolute paths under the pipeline's dir. */
function localTreeReader(root: string): (repositoryPath: string) => string | undefined {
  return (repositoryPath) => {
    const relative = repositoryPath.replace(/^\/+/, '');
    try {
      return readFileSync(path.join(root, relative), 'utf8');
    } catch {
      return undefined;
    }
  };
}

/** Keep only the named stages, in the pipeline's own order. Unknown names are a usage error. */
function applyOnlyStage(pipeline: Pipeline, only: readonly string[]): Pipeline {
  const wanted = new Set(only.map((name) => name.toLowerCase()));
  const kept = pipeline.stages.filter((stage) => wanted.has(stage.id.toLowerCase()));
  const found = new Set(kept.map((stage) => stage.id.toLowerCase()));
  const missing = only.filter((name) => !found.has(name.toLowerCase()));
  if (missing.length > 0)
    throw new CliError(`no such stage: ${missing.join(', ')}`, {
      hint: `the pipeline declares ${pipeline.stages.map((stage) => stage.id).join(', ')}`,
    });
  return { ...pipeline, stages: kept };
}

/**
 * `--only-stage` may leave a kept stage depending on a dropped one.
 *
 * Decided in docs/06 §5 decision 67: the dependency is **dropped and warned**, not refused. A
 * partial conversion is a debugging tool — refusing would make the flag useless for exactly the
 * huge pipelines it exists for — and silently keeping the reference would emit a `run.sh` whose
 * topological order names a stage that is not there.
 */
function pruneDependencies(
  pipeline: Pipeline,
  file: string,
): {
  pipeline: Pipeline;
  warnings: ManifestWarning[];
} {
  const present = new Set(pipeline.stages.map((stage) => stage.id.toLowerCase()));
  const warnings: ManifestWarning[] = [];
  const stages = pipeline.stages.map((stage) => {
    const dropped = (stage.dependsOn ?? []).filter((name) => !present.has(name.toLowerCase()));
    if (dropped.length === 0) return stage;
    warnings.push({
      code: 'E10-ONLY-STAGE-DEPENDENCY',
      message:
        `stage '${stage.id}' depends on ${dropped.map((name) => `'${name}'`).join(', ')}, ` +
        'which `--only-stage` left out; the dependency was dropped for this partial conversion.',
      location: { file, line: 1 },
    });
    return {
      ...stage,
      dependsOn: (stage.dependsOn ?? []).filter((name) => present.has(name.toLowerCase())),
    };
  });
  return { pipeline: { ...pipeline, stages }, warnings };
}

/**
 * Where the runtime library lives in the installed package, and in this repo's source tree.
 *
 * The package-name candidate is the one that has to work: it is the only spelling that resolves
 * from the **bundled** `dist/`, and it needs `@azdo-emu/runtime` declared as a dependency of this
 * package to do so. It was not, and the relative candidate below is written for the source depth
 * (`src/convert/` → `packages/runtime`), which from `dist/` points at a directory that does not
 * exist — so every conversion through the built CLI failed with "cannot locate the runtime
 * library" while the whole test suite, which runs from source, stayed green. Found by the nightly
 * drift harness (E11-S03-T01) and guarded by `packages/cli/test/packaging.test.ts`.
 */
function runtimeLibDir(): string {
  const require = createRequire(import.meta.url);
  for (const candidate of [
    '@azdo-emu/runtime/lib/core.sh',
    '../../../runtime/lib/core.sh',
    '../../runtime/lib/core.sh',
  ]) {
    try {
      return path.dirname(require.resolve(candidate));
    } catch {
      /* try the next candidate */
    }
  }
  throw new CliError('cannot locate the runtime library (lib/core.sh)', {
    hint: 'the generated project needs it; reinstall azdo-emu',
  });
}

/**
 * Every step with the `StageId/JobId/step N` path the warnings list and `neededBy` use.
 *
 * Deployment hooks are walked as well as `job.steps`: a `deploy:` hook's steps are the ones that
 * actually touch Azure in a deployment job, so a collector that read only `job.steps` would miss
 * exactly the connections this epic exists for.
 */
function stepSites(pipeline: Pipeline): readonly StepSite[] {
  const sites: StepSite[] = [];
  for (const stage of pipeline.stages) {
    for (const job of stage.jobs) {
      const at = (step: (typeof job.steps)[number]): string =>
        `${stage.id}/${job.id}/step ${step.id}`;
      for (const step of job.steps) sites.push({ step, path: at(step) });

      const strategy = job.strategy;
      if (strategy?.kind !== 'runOnce') continue;
      for (const hook of [
        strategy.preDeploy,
        strategy.deploy,
        strategy.routeTraffic,
        strategy.postRouteTraffic,
        strategy.onSuccess,
        strategy.onFailure,
      ]) {
        for (const step of hook?.steps ?? []) sites.push({ step, path: at(step) });
      }
    }
  }
  return sites;
}

/** Count the steps a scaffold plans, which is what the summary line reports. */
function countSteps(plan: Scaffold): number {
  return plan.stages.reduce(
    (total, stage) => total + stage.jobs.reduce((n, job) => n + job.steps.length, 0),
    0,
  );
}

/**
 * Convert a pipeline into a generated project.
 *
 * Returns the summary rather than printing it: the caller decides between the one-line human form
 * and `--json`, and a test can assert on the value instead of on stdout.
 */
export async function convert(
  pipelineFile: string,
  flags: ConvertFlags,
  deps: ConvertDeps = {},
): Promise<ConvertResult> {
  refuseDeferredSandbox(flags);
  checkOffline(flags);

  const loaded = loadConfigFor(pipelineFile);
  const cli: CliSettings = {
    ...(flags.org === undefined ? {} : { organization: flags.org }),
    ...(flags.project === undefined ? {} : { project: flags.project }),
    ...(flags.parameter === undefined ? {} : { parameters: flags.parameter as never }),
    ...(flags.targetOs === undefined ? {} : { targetOs: flags.targetOs }),
    ...(flags.checkoutMode === undefined ? {} : { checkoutMode: flags.checkoutMode }),
    ...(flags.groupNames === undefined ? {} : { groupNames: flags.groupNames }),
  };
  const { settings } = resolveSettings(cli, loaded.config);

  const source = readPipeline(pipelineFile);
  const warnings: ManifestWarning[] = [];

  // 1. Bundle local templates into the override (E03-S06). `--no-bundle` sends the file as authored.
  const rootDir = path.dirname(path.resolve(pipelineFile));
  const bundled =
    flags.bundle === false
      ? { yaml: source, manifestWarnings: [] as readonly ManifestWarning[] }
      : inlineTemplates(source, { read: localTreeReader(rootDir) });
  warnings.push(...bundled.manifestWarnings);

  // 2. Expand — the service by default, the retained local engine behind `--offline-expand`.
  const expanded = await resolveExpansion(
    { yamlOverride: bundled.yaml, ...templateParameters(settings) },
    {
      cacheDir: deps.cacheDir ?? path.join(flags.out, '.cache', 'expansion'),
      ...(flags.frozen === undefined ? {} : { frozen: flags.frozen }),
      ...(deps.fetchImpl === undefined ? {} : { fetchImpl: deps.fetchImpl }),
      ...(deps.oracle === undefined ? {} : { config: deps.oracle }),
      ...(flags.offlineExpand === undefined ? {} : { offlineExpand: flags.offlineExpand }),
      // The port E03-S04-T02 built and E03-S04-T03's message points here for. The queue-time
      // parameters travel with the request on both arms, so `--parameter` means the same thing
      // whichever expander answers.
      offlineExpander: (request) => ({
        finalYaml: expandDocument(request.yamlOverride, path.basename(pipelineFile), {
          ...(request.templateParameters === undefined
            ? {}
            : { parameters: request.templateParameters }),
        }).yaml,
      }),
    },
  );
  for (const warning of expanded.warnings)
    warnings.push({ code: 'E12-OFFLINE-EXPANSION', message: warning });

  // 3. Validate the expansion (E03-S04-T03) — a different dialect from the authored document.
  const diagnostics = validateExpandedPipeline(expanded.finalYaml);
  const errors = diagnostics.filter((diagnostic) => diagnostic.severity === 'error');
  if (errors.length > 0)
    throw new CliError(
      `the expanded pipeline is invalid (${errors.length} error${errors.length === 1 ? '' : 's'})`,
      {
        hint: errors
          .slice(0, 5)
          .map((d) => `${d.file}:${d.range.line}:${d.range.col}: ${d.message}`)
          .join('\n  '),
      },
    );
  for (const diagnostic of diagnostics)
    warnings.push({
      code: diagnostic.code,
      message: diagnostic.message,
      location: { file: diagnostic.file, line: diagnostic.range.line },
    });

  // 4. Build the semantic model (E04).
  const parsed = parsePipelineYaml(expanded.finalYaml, 'pipeline.expanded.yml');
  const built = buildPipeline(parsed);
  const modelErrors = built.diagnostics.filter((d: Diagnostic) => d.severity === 'error');
  if (built.pipeline === undefined || modelErrors.length > 0)
    throw new CliError('the expanded pipeline could not be modelled', {
      hint: modelErrors.map((d) => d.message).join('\n  '),
    });

  let pipeline = built.pipeline;
  if (flags.onlyStage !== undefined && flags.onlyStage.length > 0) {
    pipeline = applyOnlyStage(pipeline, flags.onlyStage);
    const pruned = pruneDependencies(pipeline, 'pipeline.expanded.yml');
    pipeline = pruned.pipeline;
    warnings.push(...pruned.warnings);
  }

  // 5. Emit (E05) and 6. write.
  const written = writeProject(pipeline, expanded.manifest, settings, warnings, {
    out: flags.out,
    expandedYaml: expanded.finalYaml,
    override: bundled.yaml,
  });

  const strictFailure = flags.strict === true && warnings.length > 0;
  const summary: ConvertSummary = {
    version: CONVERT_JSON_VERSION,
    out: flags.out,
    expansion: { mode: expanded.mode, degraded: expanded.mode === 'offline' },
    stages: written.plan.stages.length,
    jobs: written.plan.stages.reduce((n, stage) => n + stage.jobs.length, 0),
    steps: countSteps(written.plan),
    warnings: warnings.length,
    errors: 0,
    files: written.files,
  };

  if (strictFailure)
    throw new CliError(
      `${warnings.length} warning${warnings.length === 1 ? '' : 's'} with \`--strict\``,
      {
        exitCode: EXIT.strict,
        hint: `the project was written to ${flags.out}; see its README for the ranked list`,
      },
    );

  return { summary, warnings, diagnostics };
}

/** Queue-time parameters, stringified: the preview body's `templateParameters` is string-valued. */
function templateParameters(settings: ResolvedSettings): {
  templateParameters?: Readonly<Record<string, string>>;
} {
  const entries = Object.entries(settings.parameters);
  if (entries.length === 0) return {};
  return {
    templateParameters: Object.fromEntries(
      entries.map(([name, value]) => [
        name,
        typeof value === 'string' ? value : JSON.stringify(value),
      ]),
    ),
  };
}

interface WriteOptions {
  readonly out: string;
  readonly expandedYaml: string;
  readonly override: string;
}

/** Write the generated project. Returns the plan and the file count the summary reports. */
function writeProject(
  pipeline: Pipeline,
  expansion: ExpansionManifestEntry,
  settings: ResolvedSettings,
  warnings: ManifestWarning[],
  options: WriteOptions,
): { plan: Scaffold; files: number } {
  const out = path.resolve(options.out);
  const plan = scaffold(pipeline);

  // E08-S02-T01: which service connections this pipeline references, and in which mode each one
  // can actually work. Before the `.env.example` is synthesized, because it emits their blocks.
  const definitions = loadVendoredTaskDefinitions();
  const collected = collectConnections(stepSites(pipeline), definitions);
  warnings.push(...collected.warnings);
  const env = synthesizeEnvExample(pipeline, { connections: collected.connections });
  const entrypointWarnings: ManifestWarning[] = [];
  const entrypoints = emitEntrypoints(
    pipeline,
    plan,
    'pipeline.expanded.yml',
    [],
    entrypointWarnings,
  );
  warnings.push(...entrypointWarnings);

  const manifest = buildManifest(pipeline, plan, expansion, env.manifestEnv, warnings, settings);

  mkdirSync(out, { recursive: true });
  let files = 0;
  const write = (relative: string, content: string): void => {
    const target = path.join(out, relative);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, content);
    files += 1;
  };

  for (const directory of plan.directories)
    mkdirSync(path.join(out, directory), { recursive: true });
  for (const stage of plan.stages)
    for (const job of stage.jobs)
      for (const step of job.steps)
        write(step.path, emitStepScript(step.step, step.number, { taskDefinitions: definitions }));
  for (const [relative, content] of entrypoints) write(relative, content);

  write('.gitignore', plan.gitignore || GITIGNORE);
  write('.shellcheckrc', SHELLCHECKRC);
  write('.env.example', env.content);
  write('pipeline.expanded.yml', options.expandedYaml);
  write('pipeline.bundled.yml', options.override);
  write('manifest.json', `${JSON.stringify(manifest, undefined, 2)}\n`);
  write('README.md', generateReadme(manifest, plan));

  // The runtime, copied in: every emitted script sources it (decision 62).
  const lib = runtimeLibDir();
  mkdirSync(path.join(out, 'lib'), { recursive: true });
  cpSync(path.join(lib, 'core.sh'), path.join(out, 'lib', 'runtime.sh'));
  cpSync(path.join(lib, 'expr.sh'), path.join(out, 'lib', 'expr.sh'));
  files += 2;

  return { plan, files };
}

/**
 * Serialize the manifest, then fill the two fields docs/04 §11 says E05 owns and decision 64
 * deferred to this wiring: each step's emitted `file`, and each job's `targetOs`.
 *
 * They are filled here rather than in the serializer because both are facts about the *generated
 * project* — the scaffold decides the path, and the resolved settings decide the OS — and the
 * serializer sees neither.
 */
function buildManifest(
  pipeline: Pipeline,
  plan: Scaffold,
  expansion: ExpansionManifestEntry,
  env: readonly ManifestEnvEntry[],
  warnings: readonly ManifestWarning[],
  settings: ResolvedSettings,
): SerializedManifest {
  // E10-S04-T01: `tools[]` is what `doctor` reads, and until now it was always empty — the third
  // instance in this repo of a module built, tested, and never called (C-E10-035). `aggregateTools`
  // landed with E10-S04-T02's contract; nothing invoked it, so every generated project claimed to
  // need no external tools no matter how many `az`/`kubectl`/`helm` steps it contained.
  //
  // Built from the *scaffold*, not from the model, because `neededBy` records the step path the
  // generated project uses — the same spelling the warnings list and the README already use.
  const manifest = serializeManifest(pipeline, {
    expansion: expansion as never,
    env,
    warnings,
    tools: aggregateTools(toolContexts(plan)),
  });

  const paths = new Map<string, string>();
  for (const stage of plan.stages)
    for (const job of stage.jobs)
      for (const step of job.steps)
        paths.set(`${stage.stage.id} ${job.job.id} ${step.step.id}`, step.path);

  return {
    ...manifest,
    stages: manifest.stages.map((stage) => ({
      ...stage,
      jobs: stage.jobs.map((job) => ({
        ...job,
        targetOs: settings.output.targetOs,
        steps: job.steps.map((step) => {
          const file = paths.get(`${stage.id} ${job.id} ${step.id}`);
          return file === undefined ? step : { ...step, file };
        }),
      })),
    })),
  };
}

/**
 * Every step of the generated project, as the tool registry wants to see it.
 *
 * The path spelling is `StageId/JobId/step N` — identical to the one `collectConnections` and the
 * warnings list use, so a user reading "needed by: Deploy/Apply/step 2" can find that step by the
 * same name everywhere.
 */
function toolContexts(plan: Scaffold): readonly StepToolContext[] {
  const contexts: StepToolContext[] = [];
  for (const stage of plan.stages) {
    for (const job of stage.jobs) {
      for (const step of job.steps) {
        const reference = step.step.task;
        if (reference === undefined) continue;
        contexts.push({
          taskRef: `${reference.name}@${reference.version}`,
          path: `${stage.stage.id}/${job.job.id}/step ${step.number}`,
        });
      }
    }
  }
  return contexts;
}
