// @azdo-emu/fetch — REST clients. Oracle (preview endpoint) landed in E00-S03-T02;
// the expansion service (convert-time expansion step) in E00-S04-T01, its cache/lockfile in
// E00-S04-T02; auth/artifact fetchers land in E09.
export const PACKAGE_NAME = '@azdo-emu/fetch';

export {
  DEFAULT_API_VERSION,
  ORACLE_ENV_VARS,
  OracleUsageError,
  authorizationHeader,
  configFromEnv,
  organizationName,
  preview,
  previewUrl,
  redact,
  type OracleConfig,
  type PreviewOutcome,
  type PreviewRequest,
} from './oracle.js';

export {
  expand,
  expansionRequestHash,
  serializeTemplateParameters,
  provenanceFor,
  type ExpansionOutcome,
  type ExpansionProvenance,
  type ExpansionRequest,
  type FetchLike,
} from './expand.js';

// E12-S01-T01's expansion gate: the arm selector `convert` binds (E10-S02-T01).
export {
  ExpansionConfigMissingError,
  OfflineExpansionUnavailableError,
  OFFLINE_EXPANSION_WARNING,
  resolveExpansion,
  type ExpansionManifestEntry,
  type ExpansionMode,
  type OfflineExpander,
  type OfflineExpansion,
  type ResolveExpansionOptions,
  type ResolvedExpansion,
} from './expansion-source.js';

export {
  ExpansionCacheMissError,
  ExpansionError,
  cacheExpansion,
  expandCached,
  expansionCacheDir,
  finalYamlHash,
  readCachedExpansion,
  writeExpansionLockfileEntry,
  type CachedExpansion,
  type ExpandCachedOptions,
  type ExpansionLockEntry,
} from './expansion-cache.js';

export {
  AZDO_KEYRING_SERVICE,
  TOKEN_FILE_VERSION,
  AzureCredentialStore,
  CredentialStoreError,
  normalizeAzureOrgUrl,
  type AzureAuthMode,
  type CredentialBackend,
  type CredentialStoreOptions,
  type KeyringEntry,
  type KeyringLoader,
  type KeyringModule,
  type LoadedAzureCredential,
  type StoredAzureCredential,
} from './auth/storage.js';

export {
  PROFILE_API_VERSION,
  authStatus,
  credentialAuthorizationHeader,
  profileUrl,
  type AuthIdentity,
  type AuthStatusOptions,
  type AzureAuthStatus,
  type StatusFetch,
} from './auth/status.js';

export {
  GITHUB_ACCEPT,
  GITHUB_API_ORIGIN,
  GITHUB_API_VERSION,
  GITHUB_HOSTNAME,
  GitHubFetchError,
  contentsUrl,
  createGhCliTokenReader,
  fetchGitHubContents,
  fetchGitHubTarball,
  githubHeaders,
  readGhCliToken,
  resolveGitHubCredential,
  tarballUrl,
  type GhExec,
  type GhTokenReader,
  type GitHubAuthOptions,
  type GitHubContentsResult,
  type GitHubCredential,
  type GitHubCredentialSource,
  type GitHubFetch,
  type GitHubRequestOptions,
  type GitHubTarballResult,
} from './auth/github.js';

export {
  AdoGitError,
  GIT_API_VERSION,
  MIN_GIT_VERSION_CONFIG_ENV,
  extraHeaderValue,
  itemsZipUrl,
  parseGitVersion,
  readCachedSnapshot,
  readGitVersion,
  refFilterFor,
  refsUrl,
  repoCacheDir,
  resolveAdoRef,
  runGit,
  snapshotAdoRepo,
  supportsConfigEnv,
  type AdoRepoCoordinates,
  type GitRunner,
  type GitVersionType,
  type RepoFetch,
  type RepoSnapshot,
  type ResolveRefOptions,
  type ResolvedRef,
  type SnapshotMarker,
  type SnapshotMethod,
  type SnapshotOptions,
} from './repo/ado-git.js';

export {
  GITHUB_CACHE_HOST,
  GitHubRepoError,
  commitRefFor,
  commitUrl,
  githubRepoCacheDir,
  readCachedGitHubSnapshot,
  resolveGitHubRef,
  snapshotGitHubRepo,
  type GitHubRepoCoordinates,
  type GitHubSnapshot,
  type GitHubSnapshotMarker,
  type GitHubSnapshotOptions,
  type ResolveGitHubRefOptions,
  type ResolvedGitHubRef,
} from './repo/github.js';

export {
  ALIAS_ENDPOINT_SUBSTITUTED,
  ALIAS_FETCH_FAILED,
  ALIAS_LOCAL_OVERRIDE,
  ALIAS_UNKNOWN_TYPE,
  ALIAS_UNSUPPORTED_TYPE,
  DEFAULT_REPOSITORY_REF,
  REPOSITORY_TYPES,
  UNSUPPORTED_REPOSITORY_TYPES,
  adoCoordinatesFor,
  githubCoordinatesFor,
  normalizeRef,
  resolveRepositoryAliases,
  type AliasResolutionOptions,
  type AliasResolutionResult,
  type LocalRepositoryOverride,
  type RepositoryNote,
  type RepositoryOrigin,
  type RepositoryResourceSpec,
  type RepositoryType,
  type ResolvedRepository,
  type SelfRepository,
} from './repo/alias.js';

export {
  ArchiveError,
  EXTRACTED_TREE_DIR,
  commonPrefix,
  extractArchive,
  readTarEntries,
  readZipEntries,
  safeDestination,
  writeEntries,
  type ArchiveEntry,
  type ArchiveFormat,
  type ExtractionResult,
} from './repo/extract.js';

export {
  API_VERSIONS,
  OBSERVED_SERVER_MAX_API_VERSION,
  AzureDevOpsClient,
  RestError,
  negotiatedApiVersion,
  rateLimitOf,
  redactUrl,
  type ApiArea,
  type RateLimitSignals,
  type RestFetch,
  type RestRequest,
  type RestResponse,
  type RestClientOptions,
  type Sleeper,
} from './rest/client.js';

export {
  ARTIFACT_EXPAND_SIGNED_CONTENT,
  artifactCacheDir,
  downloadArtifact,
  getArtifact,
  getRun,
  listRuns,
  resolveRun,
  type ArtifactDownload,
  type DownloadArtifactOptions,
  type RunDetail,
  type RunResult,
  type RunSelector,
  type RunState,
  type RunSummary,
  type SignedArtifact,
} from './rest/runs.js';

export {
  ARTIFACT_NOT_FOUND_TYPE_KEY,
  DOWNLOADABLE_ARTIFACT_TYPES,
  downloadBuildArtifact,
  findDefinitionByName,
  getBuildArtifact,
  getDefinition,
  listBuildArtifacts,
  resolveDefinition,
  type BuildArtifact,
  type BuildArtifactDownload,
  type BuildDefinitionDetail,
  type BuildDefinitionSummary,
  type DownloadBuildArtifactOptions,
} from './rest/build.js';

export {
  envExampleBlock,
  getVariableGroup,
  getVariableGroups,
  parseVariableGroup,
  type GroupVariable,
  type VariableGroupNames,
} from './rest/variable-groups.js';

export {
  TASK_NOT_FOUND_TYPE_KEY,
  cacheTaskMetadata,
  downloadTaskZip,
  listInstalledTasks,
  parseInstalledTask,
  parseTaskReference,
  readCachedTask,
  selectTask,
  taskCacheDir,
  versionString,
  type CacheTaskOptions,
  type CachedTask,
  type InstalledTask,
  type TaskVersion,
  type TaskZipDownload,
} from './rest/tasks.js';

export {
  LOCKFILE_NAME,
  LOCKFILE_VERSION,
  LockfileError,
  canonicalizeLockfile,
  frozenFailureMessage,
  lockfileFingerprint,
  parseLockfile,
  readLockfile,
  serializeLockfile,
  verifyLockfile,
  writeLockfile,
  type Lockfile,
  type MissingPin,
  type PipelinePin,
  type RepositoryPin,
  type RootPin,
  type TaskPin,
  type VerifyOptions,
} from './lockfile.js';

export {
  DEFAULT_SCHEMA_TTL_MS,
  fetchOrgSchema,
  organizationOf,
  readCachedOrgSchema,
  schemaCachePath,
  type OrgSchemaOptions,
  type OrgSchemaResult,
  type SchemaOrigin,
} from './rest/yamlschema.js';
